version: "3.9"
name: media-stack
services:

  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent:4.6.3
    networks:
      - internal
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - WEBUI_PORT=5080
    volumes:
      - qbittorrent-config:/config
      - torrent-downloads:/downloads
    ports:
      - 5080:5080
      - 6881:6881
      - 6881:6881/udp
    restart: "unless-stopped"

  radarr:
    container_name: radarr
    image: linuxserver/radarr:5.3.6
    networks:
      - internal
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    ports:
      - 7878:7878
    volumes:
      - radarr-config:/config
      - torrent-downloads:/downloads
    restart: "unless-stopped"

  sonarr:
    image: linuxserver/sonarr:4.0.2
    container_name: sonarr
    networks:
      - internal
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - sonarr-config:/config
      - torrent-downloads:/downloads
    ports:
      - 8989:8989
    restart: "unless-stopped"

  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:1.13.3
    networks:
      - internal
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - prowlarr-config:/config
    ports:
      - 9696:9696
    restart: "unless-stopped"

  jellyfin:
    image: linuxserver/jellyfin:10.8.13
    container_name: jellyfin
    networks:
      - internal
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - jellyfin-config:/config
      - torrent-downloads:/data
    ports:
      - 8096:8096
      - 7359:7359/udp
      - 8920:8920
    restart: "unless-stopped"

  nginx:
    image: nginx:1.25.4-alpine
    container_name: nginx
    networks:
      - internal
      - external
    volumes:
      - nginx-config:/etc/nginx
      - letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    restart: "unless-stopped"

volumes:
  torrent-downloads:
  radarr-config:
  sonarr-config:
  prowlarr-config:
  jellyfin-config:
  qbittorrent-config:
  nginx-config:
  letsencrypt:

networks:
  internal:
    external: true
  external:
    external: true
