version: "3.9"
name: media-stack
services:

  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent:4.6.5
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=5080
      - TZ=UTC
    volumes:
      - qbittorrent-config:/config
      - torrent-downloads:/downloads
    restart: "unless-stopped"

  radarr:
    container_name: radarr
    image: linuxserver/radarr:5.6.0
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - radarr-config:/config
      - torrent-downloads:/downloads
    restart: "unless-stopped"

  sonarr:
    image: linuxserver/sonarr:4.0.5
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - sonarr-config:/config
      - torrent-downloads:/downloads
    restart: "unless-stopped"

  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:1.18.0
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - prowlarr-config:/config
    restart: "unless-stopped"

  jellyfin:
    image: linuxserver/jellyfin:10.9.6
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - jellyfin-config:/config
      - torrent-downloads:/data
    restart: "unless-stopped"

volumes:
  torrent-downloads:
  radarr-config:
  sonarr-config:
  prowlarr-config:
  jellyfin-config:
  qbittorrent-config:
